config/routes.rb
Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root 'new_records#index'
  get '/lp', to: 'landing_page#index'
  get '/terms', to: 'statics#terms'
  get '/privacy_policy', to: 'statics#privacy_policy'
  get '/new_records', to: 'new_records#index'
  get '/search', to: 'home#search'
  get '/near_shops', to: 'ramen_shops#near_shops'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get 'auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :ramen_shops, only: [:index, :show, :new, :create, :edit, :update] do
    member do
      get :prepare_favorite
    end
    resources :records, only: [:show, :new, :create, :edit, :update], shallow: true do
      member do
        get 'measure'
        patch 'calculate'
        get 'result'
        post 'retire'
      end
      resources :line_statuses, except: [:index, :destroy]
    end
  end
  resources :users do
    get 'favorite_shops', on: :member, as: :favorites_by
    patch 'update_test_mode', on: :member
  end
  resources :omniauth_users, only: %i[new create]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :favorites, only: [:create, :destroy]
  resources :favorite_records, only: [:index] do
    get 'filter', on: :collection
  end
  resources :likes, only: [:create, :destroy] do
    member do
      get :prepare
    end
  end
  resources :cheer_messages, only: %i[create]
  resources :shop_register_requests, only: [:new, :create, :edit] do
    get 'complete', on: :member
  end
  resources :faqs
  resources :announcements, only: %i[index show]

  namespace :admin do
    resources :announcements
  end
end

app/models/faq.rb
class Faq < ApplicationRecord
  validates :question, presence: true
  validates :answer, presence: true
  has_rich_text :detail
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  before_action :logged_in_user, only: %i[new edit create update destroy]
  before_action :admin_user, only: %i[new create edit update destroy]
  before_action :set_faq, only: %i[show edit update destroy]

  def index
    @faqs = Faq.all
  end

  def show
  end

  def new
    @faq = Faq.new
  end

  def edit
  end

  def create
    @faq = Faq.new(faq_params)

    if @faq.save
      redirect_to faq_url(@faq), notice: 'Faq was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @faq.update(faq_params)
      redirect_to faq_url(@faq), notice: 'Faq was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @faq.destroy
    redirect_to faqs_url, notice: 'Faq was successfully destroyed.'
  end

  private

  def set_faq
    @faq = Faq.find(params[:id])
  end

  def faq_params
    params.require(:faq).permit(:question, :answer, :detail)
  end
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/views/faqs/_faq.html.erb
<div id="<%= dom_id faq %>">
  <dl class="accordion-item">
    <dt class="accordion-header" id="heading<%= dom_id faq %>">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse<%= dom_id faq %>" aria-expanded="false" aria-controls="collapse<%= dom_id faq %>">
        <div class="faq-container">
          <span class="faq-icon question">Q</span>
          <div class="content">
            <%= faq.question %>
          </div>
        </div>
      </button>
    </dt>
    <dd id="collapse<%= dom_id faq %>" class="accordion-collapse collapse" aria-labelledby="heading<%= dom_id faq %>" data-bs-parent="#accordionFaq">
      <%= link_to faq, class: 'normal-link' do %>
        <div class="accordion-body">
          <div class="faq-container">
            <span class="faq-icon answer">A</span>
            <div class="content">
              <%= faq.answer %>
            </div>
          </div>
        </div>
      <% end %>
    </dd>
  </dl>
</div>

app/views/faqs/_form.html.erb
<%= bootstrap_form_with model: faq do |form| %>
  <%= form.text_field :question %>
  <%= form.text_field :answer %>
  <%= form.rich_text_area :detail %>
  <%= form.submit %>
<% end %>

app/views/faqs/edit.html.erb
<h1>Editing faq</h1>

<%= render "form", faq: @faq %>

<br>

<div>
  <%= link_to "Show this faq", @faq %> |
  <%= link_to "Back to faqs", faqs_path %>
</div>

app/views/faqs/index.html.erb
<section class="faq-section">
  <h1>よくある質問</h1>
  <div class="accordion" id="accordionFaq">
    <% @faqs.each do |faq| %>
      <%= render faq %>
    <% end %>
  </div>
  <% if logged_in? && current_user.admin? %>
    <%= link_to "New faq", new_faq_path %>
  <% end %>
</section>

app/views/faqs/new.html.erb
<h1>New faq</h1>

<%= render "form", faq: @faq %>

<br>

<div>
  <%= link_to "Back to faqs", faqs_path %>
</div>

app/views/faqs/show.html.erb
<div class="faq-show">
  <div class="faq-container question">
    <span class="faq-icon question">Q</span>
    <div class="content">
      <%= @faq.question %>
    </div>
  </div>
  <div class="faq-container answer">
    <span class="faq-icon answer">A</span>
    <div class="content">
      <%= @faq.answer %>
    </div>
  </div>
  <div class="detail">
    <%= @faq.detail %>
  </div>
  <div class="back-to-link">
    <%= link_to "よくある質問に戻る", faqs_path %>
  </div>
  <% if logged_in? && current_user.admin? %>
    <div>
      <%= link_to "Edit this faq", edit_faq_path(@faq) %> |
      <%= link_to "削除", @faq, data: { "turbo-method": :delete, turbo_confirm: "本当に削除しますか？" } %>
    </div>
  <% end %>
</div>