config/routes.rb
Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root 'new_records#index'
  get '/lp', to: 'landing_page#index'
  get '/terms', to: 'statics#terms'
  get '/privacy_policy', to: 'statics#privacy_policy'
  get '/new_records', to: 'new_records#index'
  get '/search', to: 'home#search'
  get '/near_shops', to: 'ramen_shops#near_shops'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get 'auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :ramen_shops, only: [:index, :show, :new, :create, :edit, :update] do
    member do
      get :prepare_favorite
    end
    resources :records, only: [:show, :new, :create, :edit, :update], shallow: true do
      member do
        get 'measure'
        patch 'calculate'
        get 'result'
        post 'retire'
      end
      resources :line_statuses, except: [:index, :destroy]
    end
  end
  resources :users do
    get 'favorite_shops', on: :member, as: :favorites_by
    patch 'update_test_mode', on: :member
  end
  resources :omniauth_users, only: %i[new create]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :favorites, only: [:create, :destroy]
  resources :favorite_records, only: [:index] do
    get 'filter', on: :collection
  end
  resources :likes, only: [:create, :destroy] do
    member do
      get :prepare
    end
  end
  resources :cheer_messages, only: %i[create]
  resources :shop_register_requests, only: [:new, :create, :edit] do
    get 'complete', on: :member
  end
  resources :faqs
  resources :announcements, only: %i[index show]

  namespace :admin do
    resources :announcements
  end
end

app/views/shared/_agreement.html.erb
<div data-controller="agreement">
  <div class="agreement form-check">
    <%= check_box_tag 'agreement', 'on', false, { id: 'agreement', class: 'form-check-input', required: true, data: { agreement_target: 'checkbox', action: "change->agreement#updateButtonState" } } %>
    <label for="agreement" class="form-check-label">
      <%= link_to '利用規約', terms_path, target: :_blank, rel: "noopener noreferrer" %>
      と
      <%= link_to 'プライバシーポリシー', privacy_policy_path, target: :_blank, rel: "noopener noreferrer" %>
      に同意します。
    </label>
  </div>
  <div class="d-grid">
    <%= f.submit '登録する', data: { agreement_target: 'submitButton' }, disabled: true %>
  </div>
</div>

app/views/shared/_google_login.html.erb
<div id="google-login">
  <div class="separator"><span>もしくは</span></div>
  <%= button_to '/auth/google_oauth2', method: :post, data: { turbo: false }, class: 'google-signin-button' do %>
    <span class="google-logo"></span>
    <span class="google-signin-text">Googleアカウントでログインする</span>
  <% end %>
</div>

app/views/shared/_image_uploader.html.erb
<div class="image" data-controller="image-uploader">
  <%= f.file_field :avatar, accept: "image/jpeg,image/jpg,image/png", data: { action: "change->image-uploader#displayAfterCheck", image_uploader_target: "image" } %>
  <%= image_tag '', data: { image_uploader_target: "imagePrev" }, class: 'avatar-prev', style: 'display:none' %>
</div>

app/views/shared/_search_form.html.erb
<section class="search mb-4">
  <%= search_form_for @search, url: ramen_shops_path do |f| %>
    <div class="input-group">
      <%= f.search_field :name_or_address_cont, placeholder: '店名、または住所を入力', class: "form-control",
                          value: (params[:q] ? params[:q][:name_or_address_cont] : '') %>
      <%= f.submit "検索", class: "btn btn-outline-dark" %>
    </div>
  <% end %>
</section>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>

<%= link_to user_path(@user) do %>
  <%= @user.records.not_auto_retired.count %><br>
  レコード数
<% end %>
<% if current_user? @user %>
  <%= link_to favorites_by_user_path(@user) do %>
    <%= @user.favorite_shops.count %><br>
    お気に入り店
  <% end %>
<% end %>