config/routes.rb
Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root 'new_records#index'
  get '/lp', to: 'landing_page#index'
  get '/terms', to: 'statics#terms'
  get '/privacy_policy', to: 'statics#privacy_policy'
  get '/new_records', to: 'new_records#index'
  get '/search', to: 'home#search'
  get '/near_shops', to: 'ramen_shops#near_shops'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get 'auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :ramen_shops, only: [:index, :show, :new, :create, :edit, :update] do
    member do
      get :prepare_favorite
    end
    resources :records, only: [:show, :new, :create, :edit, :update], shallow: true do
      member do
        get 'measure'
        patch 'calculate'
        get 'result'
        post 'retire'
      end
      resources :line_statuses, except: [:index, :destroy]
    end
  end
  resources :users do
    get 'favorite_shops', on: :member, as: :favorites_by
    patch 'update_test_mode', on: :member
  end
  resources :omniauth_users, only: %i[new create]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :favorites, only: [:create, :destroy]
  resources :favorite_records, only: [:index] do
    get 'filter', on: :collection
  end
  resources :likes, only: [:create, :destroy] do
    member do
      get :prepare
    end
  end
  resources :cheer_messages, only: %i[create]
  resources :shop_register_requests, only: [:new, :create, :edit] do
    get 'complete', on: :member
  end
  resources :faqs
  resources :announcements, only: %i[index show]

  namespace :admin do
    resources :announcements
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :logged_in_user, only: %i[search]
  before_action :disable_connect_button, only: %i[search]

  def search
  end

  private

  def set_search
    @search = RamenShop.ransack(params[:q])
  end
end

app/views/home/_tabmenu.html.erb
<nav class="tab-menu" data-controller="tabs">
  <ul class="tabs">
    <li><%= link_to '新着', new_records_path,           data: { tabs_target: "tab", path: new_records_path } %></li>
    <li><%= link_to '店舗検索', ramen_shops_path,        data: { tabs_target: "tab", path: ramen_shops_path } %></li>
    <li><%= link_to 'お気に入り', favorite_records_path, data: { tabs_target: "tab", path: favorite_records_path } %></li>
  </ul>
</nav>

app/views/home/index.html.erb
<%= render 'shared/search_form' %>
<section class="favorite-records mb-4">
  <h2 class="d-flex justify-content-center py-2 mt-3">お気に入り店のちゃくどん</h2>
  <% if @favorite_records&.any? %>
    <div class="records pb-2">
      <%= render @favorite_records, name: :ramen_shop %>
    </div>
    <div class="more d-grid gap-2">
      <%= link_to 'もっとみる', favorite_records_path, class: 'btn btn-outline-dark' %>
    </div>
  <% else %>
    <div class="no-records">
      <h3>まだちゃくどんレコードがありません</h3>
      <p><span>お気に入り店の</span><span>ちゃくどん報告をしよう！</span></p>
    </div>
  <% end %>
</section>
<section class="new-records mb-3">
  <h2 class="d-flex justify-content-center py-2 mt-3">新着ちゃくどん</h2>
  <div class="records pb-2">
    <%= render @new_records, name: :ramen_shop %>
  </div>
  <div class="more d-grid gap-2">
    <%= link_to 'もっとみる', new_records_path, class: 'btn btn-outline-dark' %>
  </div>
</section>

app/views/home/new_records.html.erb
<%= render 'tabmenu' %>
<section class="new-records mb-3">
  <div class="records pb-2">
    <%= render @records, name: :ramen_shop %>
  </div>
  <div class="d-flex justify-content-center">
    <%= paginate @records %>
  </div>
</section>