containers/rails/config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/about', to: 'statics#about'
  get '/terms', to: 'statics#terms'
  get '/privacy_policy', to: 'statics#privacy_policy'
  get '/ranking', to: 'home#record_ranking'
  get '/new_records', to: 'home#new_records'
  get '/favorite_records', to: 'home#favorite_records'
  get '/search', to: 'home#search'
  get '/near_shops', to: 'ramen_shops#near_shops'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :ramen_shops, only: [:index, :show, :new, :create, :edit, :update] do
    member do
      get :prepare_favorite
    end
    resources :records, only: [:show, :new, :create, :edit, :update], shallow: true do
      member do
        get 'measure'
        patch 'calculate'
        get 'result'
        post 'retire'
      end
      resources :line_statuses, except: [:index, :destroy]
    end
  end
  resources :users do
    get 'favorite_shops', on: :member, as: :favorites_by
    patch 'update_test_mode', on: :member
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :favorites, only: [:create, :destroy]
end

containers/rails/app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user
  belongs_to :ramen_shop
  has_many :line_statuses, dependent: :destroy
  has_one_attached :image do |attachable|
    attachable.variant :display, resize_to_limit: [750, 750]
  end
  accepts_nested_attributes_for :line_statuses

  attr_accessor :skip_validation, :calculate_action

  validates :comment, length: { maximum: 140 }
  validates :image, content_type: { in: %i[png jpg jpeg],
                                    message: 'のフォーマットが不正です' },
                    size: { less_than_or_equal_to: 5.megabytes,
                            message: 'は5MB以下である必要があります' }
  validate :started_at_is_recent,         on: :create, unless: :skip_validation
  validate :ended_at_is_recent,           on: :update, if: :calculate_action
  validate :ended_at_is_after_started_at, on: :update
  validate :wait_time_is_correct,         on: :update

  before_create :set_is_test_based_on_user unless Rails.env.development?
  after_create :schedule_auto_retire

  scope :not_retired, -> { where(is_retired: false, auto_retired: false, is_test: false).where.not(wait_time: nil) }
  scope :active, -> { where(auto_retired: false, is_test: false).where.not(wait_time: nil) }
  scope :ordered_by_wait_time, -> { order('wait_time DESC') }
  scope :ordered_by_created_at, -> { order('created_at DESC') }
  scope :active_ordered, -> { active.ordered_by_created_at }
  scope :top_five, -> { limit(5) }
  scope :with_associations, -> { preload(:user, :ramen_shop, :line_statuses, image_attachment: :blob) }

  def self.ranking_records
    not_retired.ordered_by_wait_time.with_associations
  end

  def self.new_records
    not_retired.ordered_by_created_at.with_associations
  end

  def self.favorite_records_from(user)
    favorite_shop_ids = 'SELECT ramen_shop_id FROM favorites WHERE user_id = :user_id'

    Record.where("ramen_shop_id IN (#{favorite_shop_ids})", user_id: user.id)
          .not_retired.ordered_by_created_at.with_associations
  end

  def calculate_wait_time_for_retire!
    update!(is_retired: true,
            ended_at: Time.current,
            wait_time: Time.current - started_at)
  end

  def auto_retire!
    update!(auto_retired: true)
  end

  private

  def set_is_test_based_on_user
    self.is_test = true if user.is_test_mode?
  end

  def schedule_auto_retire
    AutoRetireRecordJob.set(wait: 1.day).perform_later(self)
  end

  def started_at_is_recent
    return unless started_at && (started_at - Time.current).abs > 5.seconds

    errors.add(:started_at, 'は作成時の現在時刻より数秒以内でなければなりません')
  end

  def ended_at_is_recent
    return unless ended_at && (ended_at - Time.current).abs > 5.seconds

    errors.add(:ended_at, 'は更新時の現在時刻より数秒以内でなければなりません')
  end

  def ended_at_is_after_started_at
    errors.add(:ended_at, 'はstarted_atより後である必要があります。') if ended_at && started_at && ended_at <= started_at
  end

  def wait_time_is_correct
    return unless started_at && ended_at && wait_time

    return if wait_time_correct?

    errors.add(:wait_time, 'はended_atとstarted_atの差である必要があります。')
  end

  def wait_time_correct?
    calculated_wait_time = (ended_at - started_at)
    (wait_time - calculated_wait_time).abs <= 1
  end
end

containers/rails/app/controllers/records_controller.rb
class RecordsController < ApplicationController
  include RecordsHelper

  before_action :logged_in_user, except: %i[show]
  before_action :set_record, except: %i[new create]
  before_action :correct_user, except: %i[show new create]
  before_action :set_ramen_shop, except: %i[new create retire]
  before_action :check_auto_retired, only: %i[measure calculate retire]
  before_action :disable_connect_button, only: %i[measure result]

  def show
    @tweet_url = generate_tweet_url(@record, request.url)
  end

  def new
    @ramen_shop = RamenShop.find(params[:ramen_shop_id])
    @record = current_user.records.build(ramen_shop: @ramen_shop)
    @record.line_statuses.build
  end

  def edit
  end

  def create
    @record = Record.new(create_record_params)

    if @record.save
      redirect_to measure_record_path(@record), status: :see_other
    else
      set_ramen_shop
      render :new_with_errors, status: :unprocessable_entity
    end
  end

  def measure
    if @record.ended_at?
      redirect_to root_path, status: :see_other
    elsif remember_record?
      set_record_from_cookies
      flash.now.notice = '再接続しました'
    else
      remember_record
      flash.now.notice = '接続しました'
    end
  end

  def calculate
    if @record.ended_at?
      redirect_to root_path, status: :see_other
    else
      @record.calculate_action = true
      @record.update!(calculated_record_params)
      forget_record
      redirect_to result_record_path(@record), notice: 'ちゃくどんレコードを登録しました', status: :see_other
    end
  end

  def result
  end

  def update
    if @record.update(update_record_params)
      redirect_to record_path(@record), notice: '投稿しました', status: :see_other
    else
      render :result, status: :unprocessable_entity
    end
  end

  def retire
    @record.calculate_wait_time_for_retire!
    forget_record
    redirect_to root_path, notice: 'リタイアしました', status: :see_other
  end

  private

  def set_record
    @record = Record.find(params[:id])
  end

  def correct_user
    user = User.find(@record.user.id)
    return if current_user?(user)

    flash.alert = '不正なアクセスです'
    redirect_to root_path, status: :see_other
  end

  def set_ramen_shop
    @ramen_shop = @record.ramen_shop
  end

  def create_record_params
    params.require(:record).permit(:ramen_shop_id, :user_id, :started_at,
                                   line_statuses_attributes: %i[line_number line_type comment image])
  end

  def calculated_record_params
    params.require(:record).permit(:ended_at, :wait_time)
  end

  def update_record_params
    params.require(:record).permit(:comment, :image)
  end

  def set_record_from_cookies
    @record = Record.find(fetch_record_id)
  end

  def remember_record
    cookies.encrypted[:record_id] = { value: @record.id, expires: 1.day }
  end

  def forget_record
    cookies.delete(:record_id)
  end

  def check_auto_retired
    return unless @record.auto_retired?

    forget_record
    redirect_to root_path, notice: '記録は無効になっています', status: :see_other
  end
end

containers/rails/app/helpers/records_helper.rb
module RecordsHelper
  def shop_or_user(record, name)
    record.send(name).name
  end

  def remember_record?
    cookies[:record_id]
  end

  def fetch_record_id
    cookies.encrypted[:record_id]
  end

  BASE_URL = 'http://twitter.com/intent/tweet?'.freeze
  def generate_tweet_url(record, current_url)
    text = "#{record.ramen_shop.name}\n#{format_to_hms record.wait_time}でちゃくどん！"
    query = URI.encode_www_form(url: current_url, text: text, hashtags: 'ちゃくどん')
    BASE_URL + query
  end

  def format_to_hms(wait_time)
    return unless wait_time

    hours, remainder = wait_time.divmod(3600)
    minutes, seconds = remainder.divmod(60)

    format('%<hours>02d：%<minutes>02d：%<seconds>02d',
           hours: hours,
           minutes: minutes,
           seconds: seconds)
  end
end

containers/rails/app/views/records/_form.html.erb
<div id="new_line_status">
  <%= bootstrap_form_with model: @record, url: ramen_shop_records_path, data: { action: "turbo:submit-end->modal#close" } do |f| %>
    <%= f.hidden_field :ramen_shop_id %>
    <%= f.hidden_field :user_id %>
    <%= f.hidden_field :started_at, data: { modal_target: "startedAt" } %>
    <%= f.fields_for :line_statuses do |form| %>
      <%= render "line_statuses/form", f: form %>
    <% end %>
    <div class="d-grid">
      <%= f.submit '接続する', class: "button-primary", data: { action: "click->modal#fetchStartAt", disable_with: '接続中...' } %>
    </div>
  <% end%>
</div>

containers/rails/app/views/records/_new.html.erb
<%= render "modal", title: @ramen_shop.name do %>
  <%= render 'form' %>
<% end %>

containers/rails/app/views/records/_new_with_errors.html.erb
<%= render 'form' %>

containers/rails/app/views/records/_ranking_record.html.erb
<div class="records-ranking_record">
  <%= link_to record_path(record), class: 'list-group-item-action list-item' do %>
    <div class="content">
      <div class="ranking">
        <span class="rank"><%= rank %></span>
        <span class="unit">位</span>
      </div>
      <div class="record-overview">
        <%= render partial: 'records/record_overview', locals: { record: record, name: :ramen_shop } %>
      </div>
    </div>
    <div class="ps-1">
      <i class="fa-solid fa-chevron-right"></i>
    </div>
  <% end %>
</div>

containers/rails/app/views/records/_record.html.erb
<div class="records-record">
  <%= link_to record_path(record), class: 'list-group-item-action list-item' do %>
    <div class="content">
      <div class="record-overview">
        <%= render partial: 'records/record_overview', locals: { record: record, name: name } %>
      </div>
      <div class="record-extended">
        <% if record.comment.present? %>
          <div class="record-comment">
            <div class="comment-content"><%= record.comment %></div>
          </div>
        <% end %>
        <% if record.image.attached? %>
          <%= skeleton_background_tag 'record-image' do %>
            <%= lazy_image_tag record.image.variant(:display) %>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="ps-1">
      <i class="fa-solid fa-chevron-right"></i>
    </div>
  <% end %>
</div>

containers/rails/app/views/records/_record_overview.html.erb
<%= skeleton_background_tag 'avatar-image' do %>
  <%= avatar_for(record.user, :small) %>
<% end %>
<div class="record-summary">
  <h3><%= shop_or_user(record, name) %></h3>
  <div class="record-started-at">
    <%= format_datetime record.started_at %>
    <%= line_type_badge(record.line_statuses.first) %>
  </div>
  <div class="d-flex align-items-center">
    <div class="record-time">
      <%= wait_time_tag record.wait_time %>
    </div>
    <% if record.is_retired? %>
      <span class="record-status retired">リタイア</span>
    <% else %>
      <span class="record-status finished">ちゃくどん</span>
    <% end %>
  </div>
</div>

containers/rails/app/views/records/_records.html.erb
<ul>
  <% @ramen_shop.records.each do |record| %>
    <% if record.created_at.present? %>
      <li>created_at: <%= record.created_at.getutc.strftime("%F") %> 着丼: <%= record.elapsed_time.getutc.strftime("%H:%M:%S") %></li>
    <% end %>
  <% end %>
</ul>

containers/rails/app/views/records/edit.html.erb
<p><%= @ramen_shop.name %></p>
<p><%= @ramen_shop.address %></p>
<%= form_with model: @record do |f| %>
  <div class="form-group">
    <%= f.label :started_at, class:"form-label" %>
    <%= f.time_field :started_at, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :ended_at, class:"form-label" %>
    <%= f.time_field :ended_at, class:"form-control" %>
  </div>
  <%= f.submit '更新', class: "btn btn-warning" %>
<% end %>

containers/rails/app/views/records/measure.html.erb
<div class="shop-info pt-5 text-center">
  <h1 class="shop-name"><%= @ramen_shop.name %></h1>
  <small class="shop-address"><%= @ramen_shop.address %></small>
</div>
<div data-controller="timer" data-timer-started-at="<%= @record.started_at&.iso8601 %>" class="timer">
  <div data-timer-target="time">00:00:00.000</div>
  <%= bootstrap_form_with model: @record, url: calculate_record_path do |f| %>
    <%= f.hidden_field :ended_at, data: { timer_target: "endedAt" } %>
    <%= f.hidden_field :wait_time, data: { timer_target: "waitTime" } %>
    <div class="d-grid mb-3">
      <%= f.submit 'ちゃくどん！', data: { action: "click->timer#end", disable_with: 'ちゃくどん中...' } , class: "button-primary" %>
    </div>
  <% end %>
  <div class="retire d-flex justify-content-center">
    <%= link_to 'リタイアする', retire_record_path(@record), data: { turbo_method: :post, turbo_confirm: "本当にリタイアしますか？" } %>
  </div>
</div>
<div class="record-line-status">
  <div class="line-status-header border-bottom">
    <h2>行列の様子</h2>
    <%= link_to '追加報告', new_record_line_status_path(@record), data: { turbo_stream: true }, class: 'button-primary button-sm' %>
  </div>
  <div id="line_statuses">
    <%= render @record.line_statuses %>
  </div>
</div>

containers/rails/app/views/records/new.turbo_stream.erb
<%= turbo_stream.replace "modal", partial: 'new' %>

containers/rails/app/views/records/new_with_errors.turbo_stream.erb
<%= turbo_stream.replace "new_line_status", partial: 'new_with_errors' %>

containers/rails/app/views/records/result.html.erb
<div id="records-result">
  <h1 class="record-header">ちゃくどんレコード</h1>
  <div class="record-result">
    <div class="shop-info">
      <div class="shop-name"><%= @record.ramen_shop.name %></div>
      <small class="shop-address"><%= @record.ramen_shop.address %></small>
    </div>
    <div class="record-time">
      <%= wait_time_tag @record.wait_time %>
    </div>
  </div>
  <%= bootstrap_form_with model: @record, class: 'record-result-form' do |f| %>
    <%= f.text_area :comment, label: { text: "ひとこと" }, placeholder: 'ちゃくどん後の心境をどうぞ！', label_class: 'optional' %>
    <div class="image" data-controller="image-uploader">
      <%= f.file_field :image, accept: "image/jpeg,image/jpg,image/png", data: { action: "change->image-uploader#displayAfterCheck", image_uploader_target: "image" }, label_class: 'optional' %>
      <%= image_tag '', data: { image_uploader_target: "imagePrev" }, class: 'image-prev', style: 'display:none' %>
    </div>
    <div class="d-grid mb-3">
      <%= f.submit '投稿する', class: "button-primary" %>
    </div>
  <% end %>
  <div class="record-line-status">
    <h2 class="border-bottom">行列の様子</h2>
    <%= render @record.line_statuses %>
  </div>
</div>

containers/rails/app/views/records/show.html.erb
<div id="records-show">
  <div class="header">
    <h1 class="record-header">ちゃくどんレコード <span class="record-number">No. <%= @record.id %></span></h1>
    <%= link_to @tweet_url, onclick: "window.open(this.href, '_blank'); return false;", class: 'share-button' do%>
      <i class="fa-brands fa-twitter"></i> シェアする
    <% end %>
  </div>
  <div class="record-content">
    <div class="record-summary">
      <div class="shop-info">
        <div class="shop-name"><%= @record.ramen_shop.name %></div>
        <small class="shop-address"><%= @record.ramen_shop.address %></small>
      </div>
      <div class="record-time">
        <%= wait_time_tag @record.wait_time %>
      </div>
      <div class="record-duration">
        <div class="record-started-at">
          <small class='badge bg-dark me-2'>接続</small>
          <span class="date-time">
            <%= format_datetime_detail @record.started_at %>
          </span>
          <%= line_type_badge(@record.line_statuses.first) %>
        </div>
        <div class="record-ended-at">
          <% if @record.is_retired? %>
            <small class='badge me-2 retired'>リタイア</small>
          <% else %>
            <small class='badge bg-dark me-2'>着丼</small>
          <% end %>
          <span class="date-time">
            <%= format_datetime_detail @record.ended_at %>
          </span>
        </div>
      </div>
    </div>
    <% if @record.image.attached? %>
      <%= skeleton_background_tag 'record-image' do %>
        <%= lazy_image_tag @record.image.variant(:display) %>
      <% end %>
    <% end %>
    <%= link_to user_path(@record.user), class: 'user-info' do %>
      <%= skeleton_background_tag 'user-avatar' do %>
        <%= avatar_for @record.user, :middle %>
      <% end %>
      <span class="user-name">
        <%= @record.user.name %>
      </span>
      <span class="user-record-count">
        (<%= @record.user.records.count %>)
      </span>
    <% end %>
    <% unless @record.comment.blank? %>
      <div class="record-comment">
        <div class="comment-content"><%= @record.comment %></div>
      </div>
    <% end %>
  </div>
  <div class="record-line-status mb-3">
    <h2 class="border-bottom">行列の様子</h2>
    <%= render @record.line_statuses %>
  </div>
  <div>
    <%= link_to "レコード一覧へ戻る", ramen_shop_path(@record.ramen_shop) %>
  </div>
</div>